#!/usr/bin/env bash
# This Script installs Nginx on a linux server and replaces the strings contained in string

apt-get -y update
apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/error404.html
sed -i '/^\tserver_name.*/a \\terror_page 404 /error_404.html;\n\tlocation = /error_404.html {\n\troot /var/www/html/;\n\tinternal;\n\t}' /etc/nginx/sites-available/default
service nginx restart
