#!/usr/bin/env bash
# This file creates a symbolic link between sites enabled and site available
sudo apt-get purge nginx nginx-common
sudo apt-get update
sudo apt-get -y install nginx
service nginx start
