#!/usr/bin/env bash
# This is the fizz buzz func
for i in {1..100}
do
    if [ $((i % 3)) -eq 0 ]
    then
        echo "Fizz"
    fi
    if [ $((i % 5)) -eq 0 ]
    then
        echo "Buzz"
    fi

    if [ $((i % 15)) -eq 0 ]
    then
        echo "FizzBuzz"
    fi
    echo "$i"
done
