#!/usr/bin/env bash
# displays Holberton School 10 times, on the 9th item it prints it out with \n
i=0
while [ $i -le 9 ]
do
    if [ $i -eq 9 ]
    then
	echo "Hi"
    fi
    echo "Holberton School"
    ((i++))
done
