#!/usr/bin/env bash
# This gives you information on holberton school file'
if [ ! -e "holbertonschool" ]
    then
    echo "holbertonschool file does not exist"
    fi

if [ -e "holbertonschool" ]
then
    echo "holbertonschool file exists"

    if [ -s "holbertonschool" ]
    then
        echo "holbertonschool file is not empty"
    fi

    if [ ! -s "holbertonschool" ]
    then
        echo "holbertonschool file is empty"
    fi

    if [ -f "holbertonschool" ]
    then
        echo "holbertonschool is a regular file"
    fi
fi
